// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_event_lock_time_cpp
double find_event_lock_time_cpp(NumericVector enroll_time, NumericVector tte, IntegerVector event_ind, int target_n);
RcppExport SEXP _TrialSimulator_find_event_lock_time_cpp(SEXP enroll_timeSEXP, SEXP tteSEXP, SEXP event_indSEXP, SEXP target_nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type enroll_time(enroll_timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tte(tteSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type event_ind(event_indSEXP);
    Rcpp::traits::input_parameter< int >::type target_n(target_nSEXP);
    rcpp_result_gen = Rcpp::wrap(find_event_lock_time_cpp(enroll_time, tte, event_ind, target_n));
    return rcpp_result_gen;
END_RCPP
}
// find_readout_lock_time_cpp
double find_readout_lock_time_cpp(NumericVector enroll_time, NumericVector readout_time, LogicalVector observed, int target_n);
RcppExport SEXP _TrialSimulator_find_readout_lock_time_cpp(SEXP enroll_timeSEXP, SEXP readout_timeSEXP, SEXP observedSEXP, SEXP target_nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type enroll_time(enroll_timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type readout_time(readout_timeSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type observed(observedSEXP);
    Rcpp::traits::input_parameter< int >::type target_n(target_nSEXP);
    rcpp_result_gen = Rcpp::wrap(find_readout_lock_time_cpp(enroll_time, readout_time, observed, target_n));
    return rcpp_result_gen;
END_RCPP
}
// find_enrollment_lock_time_cpp
double find_enrollment_lock_time_cpp(NumericVector enroll_time, int target_n);
RcppExport SEXP _TrialSimulator_find_enrollment_lock_time_cpp(SEXP enroll_timeSEXP, SEXP target_nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type enroll_time(enroll_timeSEXP);
    Rcpp::traits::input_parameter< int >::type target_n(target_nSEXP);
    rcpp_result_gen = Rcpp::wrap(find_enrollment_lock_time_cpp(enroll_time, target_n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TrialSimulator_find_event_lock_time_cpp", (DL_FUNC) &_TrialSimulator_find_event_lock_time_cpp, 4},
    {"_TrialSimulator_find_readout_lock_time_cpp", (DL_FUNC) &_TrialSimulator_find_readout_lock_time_cpp, 4},
    {"_TrialSimulator_find_enrollment_lock_time_cpp", (DL_FUNC) &_TrialSimulator_find_enrollment_lock_time_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_TrialSimulator(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
