# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_event_lock_time_cpp <- function(enroll_time, tte, event_ind, target_n) {
    .Call(`_TrialSimulator_find_event_lock_time_cpp`, enroll_time, tte, event_ind, target_n)
}

find_readout_lock_time_cpp <- function(enroll_time, readout_time, observed, target_n) {
    .Call(`_TrialSimulator_find_readout_lock_time_cpp`, enroll_time, readout_time, observed, target_n)
}

find_enrollment_lock_time_cpp <- function(enroll_time, target_n) {
    .Call(`_TrialSimulator_find_enrollment_lock_time_cpp`, enroll_time, target_n)
}

